### ISSUE TITLE
code points vs code units

### ISSUE THREAD

**Issue by allenwb** [benjamingr/RexExp.escape#10]
You need to be careful about whether you are processing code points or code units. In particular, when you create the result string the elements must be code units so you need to reference one of the algorithms used by the spec to utf16 encode code points

**Comment by benjamingr** [comment]
Why? Doesn't it make more sense to work at the code point level and not at the code unit level?

This is what spec string algorithms do like [`toLowerCase`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.tolowercase) - I specifically didn't want to limit the algorithm to not work if for some reason something that is more than one code-unit becomes a thing in the RegExp engine.

Would you mind explaining to a relative unicode newb why a code unit level processing would be preferable?

**Comment by ljharb** [comment]
Clearly, at the moment, it doesn't matter - none of the syntax characters are surrogate pairs, nor would be lone surrogates.

However, I agree with @benjamingr - it makes sense to specify all new string operations in terms of code points rather than characters.

**Comment by allenwb** [comment]
Your main problem is in step 6: "Let *L *be a String whose elements are, in order, the elements of *cuList*."

As defined in [6.1.4)(http://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-language-types-string-type), the elements of a String are 16-bit values typically interpreted as Unicode code units. But *cuList* is a list of 20-bit Unicode code points.  So, the the elements of *L* can't be the elements of *cuList*.

You need to UTF-16 encode  *cuList* to obtain the code points for *L*. To do this include the equivalent of step 7 of [21.1.3.22](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.tolowercase).  In fact, you probably should just more carefully follow the whole pattern of [21.1.3.22](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.tolowercase) for you algorithm.

**Comment by benjamingr** [comment]
@allenwb sorry, but I'm not sure I understand. I have a list of code points in _cpList_ and a list of code points in _cuList_ and all I'm doing is moving them one by one from one list to the other list, sometimes adding an escape code point. 

Sorry for being hard - but would you mind explaining again why this is wrong or proposing a change? 

Would something like: 

>  append to cuList the elements of the UTF16Encoding (10.1.1) of c.

Instead of 

> Append c to cuList.

Work?

**Comment by allenwb** [comment]
@benjamingr
Basically, yes. a single code point has to be utf16 encoded to produce a 1 or two elements sequence to code units and individual code units are the elements that make up a string.

Here is how I would express this algorithm.  

1. Let *str* be [ToString](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-tostring)(*S*).
2. [ReturnIfAbrupt](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-returnifabrupt)(*str*).
3. Let *cpList* be a [List](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-list-and-record-specification-type) containing in order the code points as defined in [6.1.4](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-language-types-string-type) of *str*, starting at the first element of *str*.
4. Let *cuList* be a new [List](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-list-and-record-specification-type).
5. For each code point *c* in *cpList* in List order, do:
 1. If **c** is matched by [*SyntaxCharacter*](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-patterns) then do:
   1. Append code unit 0x002F (SOLIDUS) to *cuList*.
 2. Append the elements of the UTF16Encoding (10.1.1) of *c* to *cuList*.
6. Let **L** be a String whose elements are, in order, the elements of *cuList*.
7. Return **L**.

It's a bit more precise and in 5.i.a follows the conventions used in the spec when referring to specific Unicode code units.

**Comment by benjamingr** [comment]
Thanks! I'll make sure I understand this and make the relevant changes to the spec when I'm back home :)

**Comment by benjamingr** [comment]
Thanks, this makes sense
