### ISSUE TITLE
Discussion of key algorithms, abstractions and semantics

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/RexExp.escape#3]
If anyone has anything to say about the semantics of the algorithm used here, the algorithm itself or anything else - please do.

**Comment by domenic** [comment]
I think this is pretty well covered by the actual algorithm; no real work to do IMO.

**Comment by benjamingr** [comment]
Thanks, I think so too. I'm just trying to follow your lead and play nice with the process :)
