### ISSUE TITLE
Unescape?

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/RexExp.escape#8]
A lot of languages also provide a second `unescape` method like [C#](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.unescape(v=vs.110).aspx). 

Should this be considered?
If so, as a part of this proposal?

**Comment by awalGarg** [comment]
Would be nice to have an unescape method as well. Could benefit regex tooling like http://regex101.com etc. Also for consistency (like we have `String.raw`).

I think it should be a part of this proposal itself.

My 2 cents :)

**Comment by domenic** [comment]
What's striking to me is that literally nobody has ever asked for this despite the multi-year history of people asking, in es-discuss and elsewhere, for escape.

**Comment by EladRK** [comment]
When one starts to write the writing the actual code it becomes much clearer what is needed. Amusing, but it makes sense.

**Comment by benjamingr** [comment]
Yes, nothing, closing.
